### ISSUE TITLE
Ignore smart quotes

### ISSUE THREAD

**Issue by NilsFagerburg** [angstsmurf/spatterlight#1]
The OS wide "smart quote" setting interferes with some games (apostrophes in particular but I guess it could happen with other substitutions too). I think Spatterlight should probably ignore the setting and never substitute characters.

Here's a patch that seems to work with the caveat that I don't know that language so it's in all likelihood not a clean / idiomatic way of doing things.

[brol.patch.txt](https://github.com/angstsmurf/spatterlight/files/2989808/brol.patch.txt)

**Comment by angstsmurf** [comment]
I pushed a slightly modified version of this as  f529085 .

**Comment by angstsmurf** [comment]
By the way, do you have a good test case for this? Otherwise I guess I could write one myself.

**Comment by angstsmurf** [comment]
This should fixed by the changes in the new release. Let me know if it isn't. Thanks again!
