### ISSUE TITLE
Level 9 games not working?

### ISSUE THREAD

**Issue by Dion-Guy** [angstsmurf/spatterlight#11]
I'm trying to get Lancelot by Level 9 working (the DOS/Amiga/ST version), but Spatterlight doesn't seem to recognise the file format.

I have tried renaming GAMEDAT1.DAT to .sna and .l9 but regardless of the file extension it gives an error "_Babel can not identify the file format_".  I know the files are ok because they work perfectly in Gargoyle - but I'd rather use Spatterlight!

**Comment by angstsmurf** [comment]
Hmm, the version detected as "Lancelot, pt. 1 (Amiga/PC *USA*)" seems to work for me here, with all three extensions. What does Gargoyle say about the game version? Where are the game files from?

**Comment by Dion-Guy** [comment]
Thanks for the fast reply.  Gargoyle detects this version as:
Lancelot, pt. 1 (Amiga/PC/ST)

I extracted the files from a Lancelot Amiga ADF file.  I'm reluctant to post the game files publicly (or post a link as to where I got the ADF) but am happy to send them to you privately if that would be helpful?

**Comment by angstsmurf** [comment]
Sure, that would help. My address is on my Github profile page.

**Comment by angstsmurf** [comment]
Thanks!

Unlike Gargoyle, Spatterlight uses [Babel](https://babel.ifarchive.org) to detect valid game files. Babel has not been updated since 2006 and appears to have incomplete detection of Level 9 games. The actual Level 9 interpreter has its own, superior, detection code. It should be possible transplant this to Babel, but it will take a bit of work.

**Comment by Dion-Guy** [comment]
Ah ok, thanks for investigating this.  In the meantime I'll use the "Amiga/PC USA" version (which I assume is nigh on identical), but if at some point Spatterlight / Babel can support more variations of Level 9 games then that can only be a good thing.

**Comment by angstsmurf** [comment]
Fixed by 0c2ba71. Next I'd like to find out why it draws the images so small.
