### ISSUE TITLE
Update ccxvii.net

### ISSUE THREAD

**Issue by dfabulich** [angstsmurf/spatterlight#12]
http://ccxvii.net/spatterlight/ is still apparently the top hit for “Spatterlight” in Google search, and it could use some rework.

* The links point to an old v0.5.0 version, with the line, “The 0.5.0 release doesn’t work properly with more recent macOS versions” and a link at the end saying, “You can find an updated version of Spatterlight on github.” The 0.5.0 links should be removed, replaced with a single link saying, “download it from github.” The whole effect right now makes it seem as if Spatterlight just doesn’t work.
* The “screenshots” link points to ancient screenshots (what is that, OS X 10.4??). Replace that with a link to your YouTube video, or remove the link entirely.
* It’s “macOS” now, not “Mac OS X”

**Comment by angstsmurf** [comment]
I'm no web designer, but I've updated the [README.md](https://github.com/angstsmurf/spatterlight/blob/master/README.md) with images and links. Tor Andersson has also made some edits to the Spatterlight page at http://ccxvii.net/spatterlight/ . Comments are welcome.

**Comment by dfabulich** [comment]
http://ccxvii.net/spatterlight/ now links to your GitHub releases page, instead of your home page, so users may not get the benefit of the hard work you did on the readme.

**Comment by dfabulich** [comment]
As for the readme, I’d add a prominent download link.

**Comment by angstsmurf** [comment]
I think this can be closed now. Not that there isn't still room for improvement. Thanks to Tor Andersson for updating the site!
