### ISSUE TITLE
Potential crash issue - Beyond Zork

### ISSUE THREAD

**Issue by tchenqu** [angstsmurf/spatterlight#13]
Unsure whether this is a problem with my particular game file or with Spatterlight itself; attempting to use the bubble wand in Beyond Zork produces a fatal error and causes the interpreter to crash. I’m uploading a copy of the save I made right before the point at which the object in question is supposed to be utilized. Game version r60, available at Zarf's Obsessively Complete Infocom Catalog.
[BeyondZork.z5.glksave.zip](https://github.com/angstsmurf/spatterlight/files/5579045/BeyondZork.z5.glksave.zip)

**Comment by angstsmurf** [comment]
Thanks for reporting this!

Bocfel, the Z-code interpreter used by Spatterlight and Gargoyle, exits with an object out of range error at this point when you try to >BLOW BUBBLE. The command seems to work fine in Frotz and Yazmin, so this might be a case of Bocfel being overly strict.

If I simply comment out the line checking for out of range reads, the game seems to continue just fine.

**Comment by angstsmurf** [comment]
I'll upload a new build which simply skips this check later today.

**Comment by angstsmurf** [comment]
Should be fixed in https://github.com/angstsmurf/spatterlight/releases/tag/v0.6b
