### ISSUE TITLE
README.md points to resource in my repository

### ISSUE THREAD

**Issue by juandesant** [angstsmurf/spatterlight#2]
Dear @angstsmurf, first of all thanks a lot for taking care of Spatterlight! I'm very happy that getting the code into Github helped into making Spatterlight maintained 😉

The current version of the README.md points to a Credits.rtf file in my repository, but it should point to your Credits.rtf instead, or consider pointing it just to a relevant file in http://ccxvii.net/

Cheers,
Juande.

**Comment by angstsmurf** [comment]
Right, I fixed the link in 0e41624 and 5d5ac41.

I'm happy to hear that you appreciate my work on this. I was worried that you would be annoyed that I forked your repo instead of making my own from scratch.

**Comment by juandesant** [comment]
It was not even my repository to start with, I started it because it seemed to have been abandoned… I'm glad I somehow helped finding it a new home… and homeowner 😉
