### ISSUE TITLE
Pesky Bureaucracy forms

### ISSUE THREAD

**Issue by tchenqu** [angstsmurf/spatterlight#22]
Voiceover and bank slips don't seem to be getting along.
[bureaucracy-r116-s870602.z4 2021-01-31 01.56.glksave.zip](https://github.com/angstsmurf/spatterlight/files/5899504/bureaucracy-r116-s870602.z4.2021-01-31.01.56.glksave.zip)

**Comment by angstsmurf** [comment]
Hopefully fixed by 3652896
