### ISSUE TITLE
Development instructions

### ISSUE THREAD

**Issue by nk9** [angstsmurf/spatterlight#25]
I cloned the repo, opened the .xcodeproj and pressed the Build & Run button. The build succeeded, and then… nothing. I see a bunch of missing libraries under Products in the sidebar. Most importantly, the .app is also red. So I guess it wasn't actually built?

Anyway, it would be quite helpful to have a set of bootstrapping instructions for people who would like to start tinkering.

**Comment by angstsmurf** [comment]
That is bad, it is supposed to build out of the box. When developing, I often download the repo as a zip and build it from the unzipped folder (I find it easier than Git trickery to test older versions), and it always works right away.

What OS is this? Is the selected scheme Spatterlight>My Mac? It would be great if you could provide a screenshot.

**Comment by nk9** [comment]
Sure, sorry about that. This is what happens when I build from the Source .zip on 10.15.7 with Xcode 12.4:

<img width="1251" alt="Screenshot 2021-02-22 at 23 47 36" src="https://user-images.githubusercontent.com/3646730/108784944-5cdd7d00-7568-11eb-9d81-286bd6685f3b.png">

The build again succeeds, and it even starts to run. But there's an SDL2 library import error?

I think I've worked out the difference between the Source .zip and `master`. `master` is set to build the `glkimp` library target, while Source uses the `glulxe` executable target. When I switch the target, I get the same error. So… progress!

**Comment by angstsmurf** [comment]
The build target should be Spatterlight, and all the others will be built automatically. Not sure what that is not the default for you.

**Comment by nk9** [comment]
OK, almost there. All of the libraries build save the ones you called out. But the build still fails:

<img width="1480" alt="Screenshot 2021-02-22 at 23 57 48" src="https://user-images.githubusercontent.com/3646730/108785770-feb19980-7569-11eb-8747-e8067642df8a.png">

**Comment by angstsmurf** [comment]
So something seems to be wrong with the symbolic link `spatterlight/headers/SDL/SDL_metal.h`.

**Comment by nk9** [comment]
Interesting. There are actually 3 headers with broken symlinks. And indeed, when I delete the broken files and redo the symlinks, the build succeeds!

<img width="649" alt="Screenshot 2021-02-23 at 00 15 56" src="https://user-images.githubusercontent.com/3646730/108787131-0161be00-756d-11eb-8269-871b8ff24cf0.png">

Thanks very much. 😸

**Comment by angstsmurf** [comment]
Thanks a lot for noticing this. I wonder how many people have tried to build this and given up.

**Comment by angstsmurf** [comment]
Should be fixed in the current repo. Feel free to confirm.

**Comment by nk9** [comment]
Yes, master is working for me now! Thanks very much for the quick turnaround. It seems like there must be a way to have the correct target shown by defult, but thanks for including a line in the README about it for now.
