### ISSUE TITLE
Expose garglk text formatting functions

### ISSUE THREAD

**Issue by curiousdannii** [angstsmurf/spatterlight#3]
You should expose the garglk text formatting functions.

https://curiousdannii.github.io/if/gargoyle.html

The same changes for Garglk
https://github.com/garglk/garglk/commit/8f7083660100057f755a70034d429feba6f74345
https://github.com/garglk/garglk/commit/d057f8018cc0be1f9f274f10fb7c0872169c8a96

**Comment by curiousdannii** [comment]
Actually, despite the functions being in Spatterlight's glk.h, they aren't actually defined. Does Spatterlight support colour in Z-Machine or not?

**Comment by angstsmurf** [comment]
Thanks for taking a look! Any feedback at all on this code is encouraging.

No, currently Spatterlight does not support Z-Machine colours, or any of Gargoyle's extensions to Glk. I don't know why those functions are in glk.h, but I've probably been careless when copying stuff from Gargoyle.

It has been on my todo-list from the start, though, so I'll definitely look into it.

**Comment by angstsmurf** [comment]
These are implemented now.

**Comment by curiousdannii** [comment]
Wow, that's fantastic! Thank you!
