### ISSUE TITLE
glulx games "running" but not accessible

### ISSUE THREAD

**Issue by climatebrad** [angstsmurf/spatterlight#32]
on M1 MacBook Air - Big Sur 11.1

When I open Spatterlight some games (looks like only glulx games, e.g. Blue Lacuna / King of Shreds and Patches) show up in the Library and are listed in the Window menu but are inaccessible. I can't delete them from the library because Spatterlight thinks they're running. The Wand (Wand.ulx) works fine.

**Comment by angstsmurf** [comment]
That is bad. Inaccessible as in showing no game window? Do you get an alert when you double click on them in the library?

The games you mention work fine in 0.7.7 here. Did they work in Spatterlight for you at any time before this happened?

It sound like it might be a broken saved application state. Does it work if you delete the folder `~/Library/Saved Application State/net.ccxvii.spatterlight.savedState`? 

If you don't mind deleting you entire library including customised theme settings, you can also try deleting the files in  `~/Library/Group Containers/6U7YY3724Y.group.net.ccxvii.spatterlight`, and if you don't have any autosaves you want to keep, you can also as a last resort delete `~/Library/Application Support/Spatterlight`.

**Comment by climatebrad** [comment]
Deleting the application state worked. When I then launched the games they
opened in very small windows near the bottom of the screen - maybe the
windows had been launching offscreen?

**Comment by angstsmurf** [comment]
Glad to hear it worked out.

I'd really like to find a way to reproduce this. Were you upgrading from an older version when this happened? Did you move windows between screens or spaces or enter fullscreen?

**Comment by climatebrad** [comment]
It's probably a hard-to-reproduce bug. I moved from an old MacBook Pro to
an Air M1 using a Time Capsule backup.

**Comment by angstsmurf** [comment]
Fair enough. I wonder what a user friendly way to handle this would be. Some kind of force-quit command, perhaps?

**Comment by climatebrad** [comment]
Yes I would have it be an option from Delete Library - right now it ignores
running games but if I could have forced it to delete all that would have
followed my expected behavior

**Comment by angstsmurf** [comment]
Done. That was surprisingly easy.

**Comment by angstsmurf** [comment]
I'm reopening this as I managed to reproduce it (though only once, I couldn't re-reproduce it.)

This happened when opening a game by double clicking on a gblorb file in Finder, which opened Spatterlight and "started" the game in an invisible window. Deleting the autosave files seemed not to help. After restarting Spatterlight a couple of times, it opened in a tiny window which could be enlarged to make it playable. After that, it worked and I could no longer find a way to reproduce the bug.

**Comment by angstsmurf** [comment]
I have fixed one cause of this, which was that the code that autorestored file streams got confused when a game was saved with the game file on one disk and restored with it on another. But I saw it autorestore to a blank window once during an UI test after the fix, so there might still be other causes of this remaining.

**Comment by angstsmurf** [comment]
Another potential cause of this fixed: Autosave files were not properly deleted when resetting a game. Closing this now until I see it happening again.

**Comment by angstsmurf** [comment]
A similar problem was reported in the forum.

https://intfiction.org/t/spatterlight-1-1-released/62378/7

**Comment by angstsmurf** [comment]
Hopefully we can close this too, for now.
