### ISSUE TITLE
Wrong version number in 0.8.2 download

### ISSUE THREAD

**Issue by suschizu** [angstsmurf/spatterlight#34]
Hey - just noticed that the download (https://github.com/angstsmurf/spatterlight/releases/download/v0.8.2/Spatterlight.zip) still contains version 0.8.1 (instead of version 0.8.2)

<img width="231" alt="Screen Shot 2021-07-07 at 17 30 32" src="https://user-images.githubusercontent.com/16004333/124788394-94fac080-df49-11eb-998c-c135e68f5daa.png">

**Comment by angstsmurf** [comment]
Thanks for reporting this!

It is the right version, just the wrong number. Not sure how I managed to mess that up. I'll upload fixed binaries.

**Comment by angstsmurf** [comment]
Non-Yosemite version should be fixed now.
