### ISSUE TITLE
Save games in Frotz and Spatterlight

### ISSUE THREAD

**Issue by 10vorne** [angstsmurf/spatterlight#35]
Since I use Frotz on iOS and the program is not available on MacOS, I installed Spatterlight. Unfortunately, it seems that the save games of the two programs are not compatible. Frotz has a Dropbox integration to continue playing games on different devices without any problems. When I save a game (I tested it with Hibernated) in Spatterlight, the suffix of the savegame is different from that of Frotz. Would it be possible to establish compatibility here?

**Comment by angstsmurf** [comment]
Spatterlight and Frotz already use the same save format, the only difference is file extensions. Unless iOS Frotz is very different from desktop Frotz, it uses `.qzl` as extension for save files. If you replace `.glksave` with `.qzl`, save files from Spatterlight should work in Frotz. Spatterlight is able to read .qzl save files from Frotz without any renaming.

**Comment by 10vorne** [comment]
Thank you, I'll try :)

**Comment by 10vorne** [comment]
I tried to load a Frotz-Savegame of Hibernated 1 (without modification of the suffix) in Frotz and that worked. But not vice versa. Any idea?

**Comment by angstsmurf** [comment]
Seems to work fine here. What error do you get?

**Comment by 10vorne** [comment]
Perhaps it has to do with using different release version of the game. I'll check.

**Comment by angstsmurf** [comment]
Right. Save files are not compatible between different game versions in Z-machine or Glulx games.

**Comment by 10vorne** [comment]
Yes, that was the problem, different RC. Working now :)
