### ISSUE TITLE
Spatterlight beachballs on text input in macOS 15.1

### ISSUE THREAD

**Issue by sagadave** [angstsmurf/spatterlight#4]
Spatterlight Version 0.5.11b beachballs on text input in macOS 15.1 and has to be force quit. 

Resolved this issue by recompiling source in Xcode 11. 

Source fails to compile in Xcode 11 with codesign errors but this can be resolved by  

1. Adding --deep to the "Other Code Signing Flags" in the "Build Settings".
2. Then turn on "Disable Library Validation" in theSigning & Capabilities  list of the target. 

as noted in user SleepySquash's answer here: https://stackoverflow.com/questions/58195914/xcode-11-command-codesign-failed-with-a-nonzero-exit-code

Having done this a recompile fixes the text input bug.

**Comment by angstsmurf** [comment]
Thanks for looking into this! It would be interesting to know exactly what causes the Mojave build to break.

I guess I will have to install Catalina in order to investigate this, at least on a VM.

**Comment by angstsmurf** [comment]
This is weird.

 I finally installed Catalina in a VM, and was able to reproduce this with the build on Github, but not with the Lion build or with any new build I made on Mojave or Catalina. I've replaced the download [here](https://github.com/angstsmurf/spatterlight/releases/tag/v0.5.11b). 

You are welcome to try downloading it again and see if the problem still exists.

**Comment by sagadave** [comment]
Confirm the problem is not happening now running the Mojave build on 10.15.1

**Comment by angstsmurf** [comment]
Thanks for confirming this! 

Another interesting question is whether it is possible to make this project build out of the box on both 10.7 and 10.15.

**Comment by angstsmurf** [comment]
bf45cc8 seems to do it. Apple:0 Backward compatibility:1
