### ISSUE TITLE
Regression when entering commands quickly in 0.7.8

### ISSUE THREAD

**Issue by dfabulich** [angstsmurf/spatterlight#43]
Launch/restart Counterfeit Monkey. Type "yes" and "andra" to begin the game properly.

Type "n," press return, and quickly type "e" and return.

Actual: The "e" input will be lost/ignored
Expected: The "e" command should go through. This worked in 0.7.7, broke in 0.7.8, and remains broken in 0.8.8.

I thought that it might be due to the optional "Animate scrolling" feature, which was new in 0.7.8, but I tried disabling it, and it maybe sorta helped a little, but didn't fix the problem completely.

**Comment by angstsmurf** [comment]
Thanks for the feedback!

I'm have trouble reproducing this, but I think it can happen if you type *really* fast on both 0.7.7 and 0.7.8, though it is easier with smooth scrolling turned on. Which would make sense, as there never has been any caching of keypresses between commands. I wonder how hard it would be to implement.

**Comment by angstsmurf** [comment]
Not too hard, as it turns out. This should be fixed in the next release.
