### ISSUE TITLE
Preference to auto-delete missing games from the library

### ISSUE THREAD

**Issue by dfabulich** [angstsmurf/spatterlight#45]
This issue is related to #40, #41, and #44.

During IFComp, I play a lot of games that I don't intend to use/keep forever. Since I've configured Spatterlight to be the default app for `.gblorb` files, Spatterlight adds a reference to these files in its library when I double-click to open them, even if I intend to play them only once and toss them later.

When I later delete these games, they sit around in the library as missing games; this creates a chore for me to manually go through and remove those deleted games from the library.

I wish instead (as a preference? Or perhaps by default…?) Spatterlight would remove old broken library entries for me. (At the very least, I'd want a menu option to remove all library entries for missing games.)

**Comment by angstsmurf** [comment]
Please try out the new version and let me know if it is an improvement.

**Comment by dfabulich** [comment]
The new "Verify Library" option does what I want!
