### ISSUE TITLE
Quest support?

### ISSUE THREAD

**Issue by MaddTheSane** [angstsmurf/spatterlight#50]
Would it be possible to add Quest support via [geas](https://www.ifarchive.org/indexes/if-archiveXprogrammingXquest.html)?

**Comment by angstsmurf** [comment]
I added Quest 4 support to Babel on top of your Geas work, so Geas now seems to work as well as in Gargoyle. Thanks a lot!

Also, thanks for all the other much-needed fixes and cleanups that I took the liberty of cherry-picking from your fork. I hope you don't mind.

Closing this.

**Comment by MaddTheSane** [comment]
I do not mind. Go ahead 😄
