### ISSUE TITLE
Pixellated map in Counterfeit Monkey

### ISSUE THREAD

**Issue by dfabulich** [angstsmurf/spatterlight#51]
On HiDPI Mac, launch Counterfeit Monkey at a large window size. The map's image is a little bit pixellated, as if it's not properly showing in HiDPI mode. (Or maybe my eyes are playing tricks on me?)

I'm on a MacBook Pro 16" 2021.

<img width="2094" alt="Screen Shot 2021-11-13 at 5 00 05 PM" src="https://user-images.githubusercontent.com/96150/141663553-8e03d3d3-b99a-4a5f-ab03-f93ac92bef25.png">

It should look like this, right? https://raw.githubusercontent.com/i7/counterfeit-monkey/master/Counterfeit%20Monkey.materials/Large-map.png

**Comment by angstsmurf** [comment]
No, the Large-map.png file is much larger than the [in-game map](https://github.com/i7/counterfeit-monkey/blob/master/Counterfeit%20Monkey.materials/Figures/map-back-alley.png) (3008 x 3583 pixels vs 772 x 860.) You should look at the map images in the Figures folder.

If you want to see what it looks like in non-HiDPI, you could just open the game in Gargoyle. The difference is pretty big.
