### ISSUE TITLE
Using RESTART command ends transcript

### ISSUE THREAD

**Issue by aubloom** [angstsmurf/spatterlight#57]
In my experience with Gargoyle, Lectrote, etc., if you're playing a game and recording a transcript, and you RESTART, the transcript keeps going. I did this with a z5 game in Spatterlight yesterday and when I went to look at the transcript, it had ended after the RESTART command was entered.

I don't know if this is just a helpful feature interpreters have adopted, or an expected behaviour that Spatterlight isn't performing, but it would be great to have it added.

**Comment by angstsmurf** [comment]
I tried to fix this in the new release ([0.9.2](https://github.com/angstsmurf/spatterlight/releases/tag/v0.9.2)). This bug manifests a bit randomly, so it is hard to tell whether it is actually fixed or whether you are just being lucky.
