### ISSUE TITLE
Cover art not displaying with Show Info

### ISSUE THREAD

**Issue by aubloom** [angstsmurf/spatterlight#59]
I'm using Spatterlight 0.90 on macos 12.4.

I've just compiled a game in Inform 6M62 with the 'release along with cover art' option. The cover is 960 x 960 with a resolution of 72 dpi. The file name is Cover.jpg

When I choose 'Show Info' in Spatterlight, I see Inform's default brown cover graphic. However I know the cover art made it into the gblorb, because if I ask Lectrote to Display Cover Art, it shows it to me.

I tried a 12-year-old game with cover art in Spatterlight, and the art showed up fine. So, I don't know if this is Mac / macos-related (i.e. something about the way the graphic is handled by Inform on my setup makes a file Spatterlight can't interpret? Just my stab in the dark guess.)

**Comment by angstsmurf** [comment]
Thanks for the report!

It is hard to be sure what is going on here. Spatterlight tries to detect the Inform 7 placeholder image, so it might be a MD5 checksum collision, but that is unlikely. More likely it has at some point stored the placeholder image as cover art for this game in its database, and now it is not updating it for some reason.

Does it work if you delete the game from Spatterlight, prune the library (Hold down the option key to turn File > Delete Library into File > Prune Library) and then add the game again?

Would it be possible to share the gblorb file or the image?

**Comment by aubloom** [comment]
Thanks. After flushing all memory of the game from Spatterlight and reopening it there, the cover art appeared.

**Comment by angstsmurf** [comment]
I'm thinking that this might be due to the option in Preferences > Global > "When importing data" being set to "Don't replace images". But it is supposed to detect the placeholder image and always replace that anyway, so something is not working as intended.

**Comment by aubloom** [comment]
Looking in that preference section, I see mine is already set to 'Always replace images.' I don't think I've ever altered any of the Global preferences.

**Comment by angstsmurf** [comment]
Turns out this was more of an unimplemented feature than a bug. Should be fixed with 6b8558c.
