### ISSUE TITLE
Update Git?

### ISSUE THREAD

**Issue by curiousdannii** [angstsmurf/spatterlight#62]
I see that Git hasn't been updated for 6 years. Is that because Glulxe is used instead? If the user can choose Git then it will need to be updated for the new opcodes etc.

**Comment by angstsmurf** [comment]
I'm not sure why the Git source is in the repo at all. It was never included in the project or used for anything at all. Tor Andersson probably planned to add it as an alternative to Glulxe, but never got around to it (until he added both to Gargoyle instead.)

The source should perhaps be removed, unless someone really wants Git to be added. There is no mechanism to select which interpreter Spatterlight uses for a game anyway.

**Comment by curiousdannii** [comment]
Ah, okay. Good to know.
