### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [angstsmurf/spatterlight#64]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CVmFormatter](https://github.com/angstsmurf/spatterlight/blob/4d7ef1af56598ba38fad287cb2d9eae96775a0ef/terps/tads/tads3/vmconsol.cpp#L231 "Destructor for CVmFormatter")
- [CVmObjDict::notify_delete](https://github.com/angstsmurf/spatterlight/blob/4d7ef1af56598ba38fad287cb2d9eae96775a0ef/terps/tads/tads3/vmdict.cpp#L260 "CVmObjDict::notify_delete function")
- [vm_run_preinit](https://github.com/angstsmurf/spatterlight/blob/4d7ef1af56598ba38fad287cb2d9eae96775a0ef/terps/tads/tads3/vmpreini.cpp#L95 "vm_run_preinit function")

**Comment by angstsmurf** [comment]
Thanks! I'll look into it. I really should try to learn C++ properly one of these days.

As these are all in the Tads 3 source, the people over at [the main Tads repo](https://github.com/tads-intfic/tads-runner/issues) might appreciate this as well.

**Comment by elfring** [comment]
>As these are all in the Tads 3 source, …

Is the “Text Adventure Development System” still maintained?

**Comment by angstsmurf** [comment]
The repo over at https://github.com/tads-intfic/tads-runner is an attempt to maintain it. There hasn't always been a huga amount of activity there, but there was an update two weeks ago. I'm sure they will be glad for any contributions.

**Comment by elfring** [comment]
:thought_balloon: Can similar update candidates be found also for other software components?

**Comment by angstsmurf** [comment]
Look, don't take this the wrong way, but I'm not a 100 percent sure I'm talking to a human being here.

**Comment by elfring** [comment]
:crystal_ball: It seems to become more popular to present an assumption according to “ChatGPT”.

-----

:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
