### ISSUE TITLE
agt2agx not running under Mojave in latest versions of Spatterlight

### ISSUE THREAD

**Issue by Nephar** [angstsmurf/spatterlight#67]
Is there a reason why **agt2agx** executable is not running in Mojave but Spatterlight and Agility terp themselves are working fine? It gives "illegal instruction: 4" when run from the command line. This also causes Spatterlight itself choke on running AGT's **.D$$** files (like _Klaustrophobia_'s **klaus1.d$$**), since Spatterlight seems to convert them to agx format before running Agility interpreter.

The last version of agt2agx that is working under Mojave seems to be from Spatterlight 0.8.8 Yosemite build.

Checked in Spatterlight 0.9.9

**Comment by angstsmurf** [comment]
Thanks for reporting this! It is apparently broken in all sandboxed builds. I'll look into it.

**Comment by angstsmurf** [comment]
If you want a temporary workaround, it seems that it works if you select Add to library (not Open file) and then select a directory that contains the .D$$ and related files, not the file itself.

**Comment by Nephar** [comment]
Nice workaround. I was using the **agt2agx** from 0.8.8 to convert to agx, then Spatterlight runs the agx file fine.

Btw, you might want to also touch the misleading error message in Spatterlight terp call. It suggests that the agt file is an older style one and can't be converted to agx, regardless of the actual error **agt2agx** returns:

<img width="420" alt="Screen Shot 2023-02-15 at 21 47 15" src="https://user-images.githubusercontent.com/122389007/219124955-97106b36-64ca-4dd2-a1e9-2b3c98f40861.png">
