### ISSUE TITLE
Error when trying to launch Spatterlight with sudo

### ISSUE THREAD

**Issue by Nephar** [angstsmurf/spatterlight#70]
While trying to investigate the themes and missing fonts issue I have encountered an error.

`sudo /Applications/Spatterlight.app/Contents/MacOS/Spatterlight` causes _Illegal instruction: 4_.

Works fine without sudo. Tested with Spatterlight 0.9.9 under Mojave.

**Comment by angstsmurf** [comment]
This seems related:
https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

If I understood it correctly, it tries to call some library that isn’t present in Mojave.

**Comment by angstsmurf** [comment]
By the way, you could probably build Spatterlight yourself on 10.14 without too much hassle, if you feel like investigating further.

**Comment by Nephar** [comment]
Unfortunately my old XCode installation needs some updates applied, but their certifications have expired by Apple. I know the way to bypass those issues, but I am reluctant to do so. I don't want to break something inadvertently, since I am still using this computer for some work.

Should I close this then?

**Comment by angstsmurf** [comment]
I'm fine either way. It would be interesting to find out why it happens.

**Comment by angstsmurf** [comment]
Judging by the comments to [this stackoverflow question](https://stackoverflow.com/questions/49589998/how-to-run-a-macos-app-as-root-and-use-system-calls), this seems to be the expected result when trying to run a sandboxed app with sudo. I suppose that is enough of an explanation.
