### ISSUE TITLE
Animate scrolling locks up under certain condition

### ISSUE THREAD

**Issue by Nephar** [angstsmurf/spatterlight#75]
After a /replay of a long command log in Bocfel (for a z5 file compiled by Dialog), if I press <kbd>Cmd</kbd>+<kbd>&darr;</kbd> (Cmd+down arrow) before typing anything else, scrollback buffer starts scrolling down slowly(about one page per second and it gets slower as it gets closer to the end of the buffer) and the animation can't be escaped until it run its course to EOF or by shutting down the program.

Clearing `Animate scrolling` checkbox resolves the issue.

**Comment by angstsmurf** [comment]
Heh. The "slow scrolling" is meant to be clipped at a maximum of 0.3 seconds to scroll to the bottom, but apparently I used a MAX() macro where I should have used MIN(). This will be fixed in the next release.

**Comment by angstsmurf** [comment]
By the way, do you happen to have a good test case of this which you are willing to share?

**Comment by Nephar** [comment]
Sure, this is my WIP port of advent430 from ESR's [Open Adventure](https://gitlab.com/esr/open-adventure) (which is itself a port of adv430) and a 328 turns max score walkthrough log (from [the issues board of Open Adventure](https://gitlab.com/esr/open-adventure/-/issues/61)) to replay. Obviously, this spoils the game completely.
Just `/replay` **328.txt** as soon as the game starts, wait for the game over and hit <kbd>Cmd</kbd>+<kbd>&darr;</kbd>.
[advent430.zip](https://github.com/user-attachments/files/15522261/advent430.zip)

**Comment by angstsmurf** [comment]
Thanks!

**Comment by angstsmurf** [comment]
By the way, until the next release, you can work around this problem by just simply pasting or opening the command script directly at the command prompt instead of using the ` /replay ` command.

**Comment by Nephar** [comment]
Aha, I had no idea that **File->Open...** could be used for command scripts. (Now if I could only use Bocfel from the terminal, all my problems would go away. But that's nothing to do with this issue, I just have to bite the bullet and try to link Bocfel to the CheapGlk.)

**Comment by angstsmurf** [comment]
I wrote some instruction to on how to build and link Glulxe with CheapGlk [here](https://github.com/i7/counterfeit-monkey/tree/master/tools#building-a-profiling-enabled-glulxe-on-macos). No idea if they are helpful, or how to adapt them to Bocfel.

**Comment by Nephar** [comment]
Thanks, every bit of information helps. Zarf said to look at the build notes in [https://github.com/erkyrath/cheapglk](https://github.com/erkyrath/cheapglk). Between this

> When you compile a Glk program and link it with GlkTerm, you must supply
one more file: you must define a function called glkunix_startup_code(),
and an array glkunix_arguments[]. These set up various Unix-specific
options used by the Glk library. There is a sample "glkstart.c" file
included in this package; you should modify it to your needs.

and your instructions, I might have a chance at managing this.
