### ISSUE TITLE
String typo in GlkController.m

### ISSUE THREAD

**Issue by Nephar** [angstsmurf/spatterlight#76]
In [GlkConroller.m](https://github.com/angstsmurf/spatterlight/blob/9e9baf481c7fec84d491930fa917ecea47486b8b/application/GlkController.m#L2422), _Recordning_ -> _Recording_
```
        case fileusage_InputRecord:
            prompt = @"Save recording: ";
            ext = @"rec";
            filename = @"Recordning of ";
            break;
```

**Comment by angstsmurf** [comment]
Thanks!
