### ISSUE TITLE
VoiceOver reads the entire response from the beginning at any key presses in ZMachine games

### ISSUE THREAD

**Issue by AERobert** [angstsmurf/spatterlight#78]
A good example of what I mean can be found at the start of [The Cube in the Cavern](https://ifdb.org/viewgame?id=bif1htzf96yn9u6d). After the initial question, there is several "wait for any key" prompts before the main game starts. After each key press, Voiceover reads out all the text since your answer to the question. Its also present in all other ZMachine games I have tried, such as Spider and Web.

It does not seem to happen in Glulx or any other formats. It also doesn't seem to appear right after a screen clear or when the game wants you to hit specific keys, as in the start of [Heroes](https://ifdb.org/viewgame?id=j1uj9pygpuw3v9pc).

I am running Spatterlite 1.1 under MacOS Sonoma 14.5.

**Comment by angstsmurf** [comment]
Thanks for spotting this!

This was a pretty serious bug that must have existed for at least four years. The fix seems almost too easy, so it wouldn't surprise me if it breaks something else.

I'm in the process of uploading a beta version that will hopefull work better for you, but Github upload seems slow today.

Don't hesitate to report any other bugs you may find.

**Comment by angstsmurf** [comment]
Upload seems to be extremely slow. You may want to try this temporary link instead: https://sprend.com/download?C=e977203e308d4a8c84eacde946d5f749

When testing, it would would be great if you could confirm that the command history rotor (activated with VO + U) works as expected. I've reports of this being buggy see #26.

**Comment by AERobert** [comment]
Wow, thank you for looking into this so quickly. So far, the tests I have been doing with the beta look good, the issue with key presses seems to be gone and I haven't found any related bugs yet.

In version 1.1, the command history (the one accessed through the up / down arrows) randomly breaking was becoming a pretty common issue for me, but it hasn't happened yet in 1.2. I always forget about the command history / scroll up feature in the rotor, so I can't  say how bugged it was in previous versions, but in 1.2 it seems to be working as intended. Although, I still find it somewhat confusing that it starts at the top with the latest output and has the history going backwards down the rotor, instead of the opposite way like the command history on the input line.

There are a few more bugs I've encountered, which I will try to make issues for later.

**Comment by angstsmurf** [comment]
Sounds great!

Looking at the code, it might actually be possible to turn the command history rotor upside down, but the custom rotor API is not very customisable. I'll see what I can do.

**Comment by angstsmurf** [comment]
I suppose that means we can close this.
