### ISSUE TITLE
VoiceOver gets very confused when playing Junior Arithmancer

### ISSUE THREAD

**Issue by AERobert** [angstsmurf/spatterlight#82]
I'm not 100% sure if this is a bug in Spatterlight, but in [Junior Arithmancer](https://ifdb.org/viewgame?id=pw1rbjt1t4n4n87s) there is a side window where your full task list is shown. Unfortunately, this window seems to confuse Voiceover so that it seems to read from the statusline instead of the main game text, it also seems to interpret it as a menu? I know that at one point, it was possible to play it by turning off the window using "WINDOW OFF" which still works temperarily, but it breaks again as soon as I try doing one of the games spells. Specifically, the commands "SPELLS" or "STA 0" break it again.

I haven't found any other games which behave like this, even ones with complicated window setups like [the Time Machine V2.0](https://www.springthing.net/2024/stories/TheTimeMachineV20/TheTimeMachine-v2.gblorb) seem to work fine in VO, but it would be really nice if this could be fixed in JA.

I have experienced this behavior in both 1.1 and 1.2.

**Comment by angstsmurf** [comment]
The menu detection code definitely needs a little love, but for now I've just added a hard-coded check for this particular game. By the way, in the preferences you can select VoiceOver > Speak menu lines > Don't detect menus, which is meant to be used to deal with this kind of false positives.

Implemented in test build 1.2.1:
https://github.com/angstsmurf/spatterlight/releases/tag/v1.2.1b

**Comment by AERobert** [comment]
Thanks. I had used the menu detection feature in the past, but had forgotten about it. 

Just in case this points to another bug, I was checking if changing the setting worked to fix JA in the release version, and I found that if I changed the setting while the game was running and Spatterlight thought I was in a menu it just broke the game and it stopped speaking all together. It worked if I changed the setting and then opened JA.

Either way, the fix you  put in seems to be working fine in the new version.

**Comment by angstsmurf** [comment]
There was a problem with "removing" already detected menus when turning off menu detection in the settings. 765a021 should fix it. I also made the menu detection disabled by default, and tried to improve the tooltip of the setting.

**Comment by angstsmurf** [comment]
This should be fixed now.

**Comment by AERobert** [comment]
I just retested the game in V1.2.4, as I saw you had replaced the game-specific code with a more general fix. The game starts out fine, but if I specifically examine the spells list in the game twice, it detects the menu again. Just turning off all menu detection does fix it for me though.

**Comment by angstsmurf** [comment]
Thanks! I think I'll just have to reinstate the game-specfic fix.
