### ISSUE TITLE
Enter presses seem to be ignored when games start

### ISSUE THREAD

**Issue by AERobert** [angstsmurf/spatterlight#84]
When I open a game before typing anything, I am unable to just submit a empty command with enter or get a response from the, empty, command history arrowing up and down until I type at least one character. I like being able to just hit enter to check if the game is responding normally.

Experimenting more, it seems this also applies to "wait for any key" prompts at the beginning of games. For instance, in [According to Cain](https://ifdb.org/viewgame?id=6qp3g7te26h3rb5u) it takes about 5 presses of the enter key for it to be recognized by the game and for it to continue, while hitting "l" once is immediately recognized.

**Comment by AERobert** [comment]
Ok, looking at more games, it seems like the second part of the issue may only happen with certain games, I think with multiple consecutive wait for any key presses at the start? For instance, [Junior Arithmancer](https://ifdb.org/viewgame?id=pw1rbjt1t4n4n87s) responds responds to enter correctly to get passed the first screen, but [The Little Match Girl and Her Friend, the Crow](https://ifdb.org/viewgame?id=jiyuujd43sqx3fu0) is, a game with several key presses required at the start, does no respond normally to enter at firstt.

**Comment by angstsmurf** [comment]
I suspect that the key presses are actually working fine, and that the issue is VoiceOver giving no feedback.

I'll try to find a fix.

**Comment by angstsmurf** [comment]
This might be improved in 1.2.2b.
https://github.com/angstsmurf/spatterlight/releases/tag/v1.2.2b

**Comment by AERobert** [comment]
Thank you for looking into this.

The new build does seem to have improved this a bit, though its still definitely present. It is not consistant, opening Spider and Web for example sometimes requires me to press entr twice and sometimes 9 times to be excepted for the first time. These do seem to be recognized by the system as they will quickly stop VO from speaking, but otherwise they don't seem to have any effect. Copying and pasting the game's text also doesn't show any "I beg your Parden?" messages showing up so I am still not sure if it is a problem with VO or not. As for the two games I noted with problems on initial start up, According to Cain now usually lets me press enter to get past the first text, but then requires two presses to get to the actual game. While the Little Match Girl game I mentioned still does not respond to enter until I press it 10 times, it is consistant that it will respond on the tenth press.

**Comment by angstsmurf** [comment]
Right, I think I know what is happening now. Sorry it took me so long.

If a game prints more text in a single "move" than fits in the window, Spatterlight will enter its "more prompt" mode. Unlike most other IF interpreters, Spatterlight won't actually display the word "More", but it will behave in a similar way, waiting for the user to take action until it displays more of the text.

In this mode, the Enter key will scroll down one line, as will the down arrow key. Space bar will scroll down one entire screen, just like Page Down / Command + down arrow. Any letter and most other keys will scroll down all the way to the input prompt, ending the "more prompt" mode.

This is obviously confusing for a VoiceOver user that can't tell what is going on, so I guess the solution is to  entirely disable this mode when VoiceOver is active and always scroll to the bottom right away.

**Comment by angstsmurf** [comment]
5d7c48f should fix this.

**Comment by angstsmurf** [comment]
Implemented in 1.2.4b:
https://github.com/angstsmurf/spatterlight/releases/tag/v1.2.4b
