### ISSUE TITLE
Doesn't detect status windows in most TADS 3 games

### ISSUE THREAD

**Issue by AERobert** [angstsmurf/spatterlight#85]
I like using the speak status shortcut often when I am playing. Unfortunately, this fails in most TADS 3 games (TADS 2 games work fine) with the message, "No status window found!" Even when there is a clear status area. Although in these cases, the status window shows up as an "edit text" field using VoiceOver, so I expect something deeper may be going wrong.

Some games where I can find this behavior include: [Gun Mute](https://ifdb.org/viewgame?id=xwedbibfksczn7eq), [Return to Ditch Day](https://ifdb.org/viewgame?id=sicva377zqygxcq2), [], and [According to Cain](https://ifdb.org/viewgame?id=6qp3g7te26h3rb5u). The only T3 game I have found so far that does have a detectable statusline is [I am Prey](https://ifdb.org/viewgame?id=1vaafzgrqf4m8yvr), at least after the starting screens.

**Comment by angstsmurf** [comment]
Thanks for pointing this out!

The Speak status action simply looks for a  Glk grid window, but TADS will often use a buffer window instead for the status window (if you're not familiar with the Glk screen model, grid windows are basically guaranteed to use a fixed-with font and not scroll.) This never crossed my mind before. We will have to come up with a different solution for those games.

**Comment by angstsmurf** [comment]
I implemented something that seems to work in test build 1.2.2b. Not tested with a lot of TADS 3 games, though:
https://github.com/angstsmurf/spatterlight/releases/tag/v1.2.2b

**Comment by AERobert** [comment]
I have tried the new build on all the t3 games  I downloaded when testing if this was an actual bug, and they all seem to speak it fine now. Thanks for the fix!

**Comment by angstsmurf** [comment]
Excellent. Closing this for now, then.
