### ISSUE TITLE
Suggestion: option to speak title of game along with the last move when switching to a game window.

### ISSUE THREAD

**Issue by AERobert** [angstsmurf/spatterlight#89]
I've been experimenting with the new interruption controls and currently I prefer them on with a 0% delay, which immediately announces the last move when I switch to a game window, along with other effects I may not have noticed yet.

Unfortunately, it skips announcing the title of the current game window I've focused on. This makes it difficult to know which game I'm in sometimes.

So would it be possible to add an option that speaks the game title before announcing the last move or something similar?

**Comment by angstsmurf** [comment]
This is now implemented in test build 1.2.3b, but only kicks in if the interruption delay is set to 0. Perhaps it should be used for all delays below one second or similar? 

https://github.com/angstsmurf/spatterlight/releases/tag/v1.2.3b

**Comment by angstsmurf** [comment]
In build 1.2.4b, the game title is spoken if delay is set to below one second.

https://github.com/angstsmurf/spatterlight/releases/tag/v1.2.4b

**Comment by AERobert** [comment]
Thanks, this has been working well when the interruptions work as intended, even if their behavior isn't nearly as consistent as I thought in my first tests.

**Comment by angstsmurf** [comment]
Great! We can close this, then.
