### ISSUE TITLE
Wow!  sound support for inform?

### ISSUE THREAD

**Issue by richtw370** [angstsmurf/spatterlight#9]
First of all thanks for the work and the update....I had been worried about playing interactive fiction under Catalina until I came across this.

For those infocom games that also had sound effects, does Spatterlight support that (blb files or otherwise) and are there any install steps I need to take note of?

sorry to waste  your time...dug into the credits and see you are using from 2.50....checked git for that and see that it support blb, so I should be all set :)

**Comment by angstsmurf** [comment]
No, sorry. The old Infocom games with sound effects don't play any sounds in Spatterlight yet. I'm working on it.

Until then, it is possible to build [Frotz](https://gitlab.com/DavidGriffith/frotz) from source on Catalina and play Sherlock and The Lurking Horror with fully working sound.

**Comment by angstsmurf** [comment]
Full sound support for Sherlock and The Lurking Horror in 0.5.13b!
