### ISSUE TITLE
Zork Zero: Up arrow key doesn’t go back to previous command

### ISSUE THREAD

**Issue by dfabulich** [angstsmurf/spatterlight#95]
https://intfiction.org/t/spatterlight-release-1-2-5-is-out/70302/10?u=dfabulich

> The up arrow works in Gargoyle and glkterm, but it looks like Zork Zero does add it as a terminating key, so maybe there’s some weird interaction there. Something (yet again) @angstsmurf and I may be able to work out the source of.

**Comment by angstsmurf** [comment]
*Zork Zero* and *Shogun* lets you navigate using the arrow keys and the keypad. ↑ means go north, → east and so on. This can also be customised in the DEFINE menu to make the arrow keys mean any arbitrary command.

In Spatterlight, there is the setting "Beyond Zork arrow keys" where you can set how much of this to support. With the "Replaced by ⌘↑ and ⌘↓" setting, it can be turned off entirely, restoring the standard behaviour of all arrow keys.

In 1.2.5, this only works for *Beyond Zork*, but after fd827a6 it should work in *Zork Zero* and *Shogun* as well.
