### ISSUE TITLE
VoiceOver does not automatically read Game Output in Sequoia 15.1

### ISSUE THREAD

**Issue by slannon97** [angstsmurf/spatterlight#97]
The subject says it all. I tried running the latest public version from both the Mac App Store and GitHub, as well as the latest test version. I used The Dreamhold from https://ifdb.org/viewgame?id=3myqnrs64nbtwdaz for this test. VoiceOver seems like it's going to automatically read after I type a command, then interrupts itself by saying space and says nothing. Is this a problem with Sequoia? I'm using an M4 Mac mini.

**Comment by angstsmurf** [comment]
Thanks for reporting this. It indeed seems to be a Sequoia problem. Very annoying, especially condsidering all of the VoiceOver testing we did before releasing version 1.2.5.

I'll try to find a fix.

Do you happen to know if it worked before 15.1?

**Comment by slannon97** [comment]
I have no idea. The last time I used the program for extended periods of time was on Big Sur using a 2013 MacBook Air. I just received this Mac mini and it comes with Sequoia. Was the testing done in Sonoma, the initial version of Sequoia, or both? Perhaps Apple changed something between either the last version of Sonoma to Sequoia, or between 15.0 to 15.1.

**Comment by angstsmurf** [comment]
Thanks. All the testing was done in Sonoma. I've done a lot of VoiceOver work in Sequoia as well, but it was all focused on _Journey_, which doesn't use a text parser, so I totally missed this problem.

**Comment by angstsmurf** [comment]
The problem seems to be a "selected text changed" notification, which are issued when the input cursor moves to its new position at the prompt. This will speak the text to the left of the new cursor position, interrupting the speaking of the game output.

No idea why this didn't happen on previous systems.

Simply adding delays everywhere seems to fix the problem. I'll try to get a test version up later today.

**Comment by angstsmurf** [comment]
Test build ready. I've just added a delay and increased the length of a couple of existing ones.

It would be great if you could try it out:
https://github.com/angstsmurf/spatterlight/releases/download/v1.2.6.4/Spatterlight.zip

**Comment by slannon97** [comment]
I just tried the newest version. VoiceOver now reads the > prompt when typing commands. I tried disabling the read command and interrupt settings, but this doesn't help. I can read the output with the paragraphs rotor. The line and command history rotors don't seem to be reliable either, at least in the Dreamhold. COmmand history seems to read either the output from the last command, or the information at the very top of the history, and line appears tobe skipping information seemingly at random. Do these depend on the game?

**Comment by angstsmurf** [comment]
Thanks for giving it a spin!

I'm sorry to say, I cannot seem to reproduce the problems you describe, although I noticed some other issues and tried to alleviate them.

Does this version make any difference?
https://github.com/angstsmurf/spatterlight/releases/download/v1.2.6.5b/Spatterlight.zip

**Comment by angstsmurf** [comment]
Another tip is to switch off animated scrolling in Settings > Details > Animate Scrolling. It is the bottom checkbox.

This seems to stop VoiceOver from making an annoying little beep when scrolling.

**Comment by slannon97** [comment]
Whatever you did fixed the problem. This should definitely go into the next public release. Thank you for the tip about scrolling. That beep from VoiceOver is very annoying! I'm once again delighted to say this is by far the best IF interpreter for a blind person on any platform! I love the automatic speech output. Thank you so much for everything you do.

**Comment by angstsmurf** [comment]
I'm happy to hear that.

I still think that there is a fundamental problem with how VoiceOver interacts with the text views of Spatterlight, and I don't know how to fix it.

It is possible that asking all VoiceOver users to change the verbosity settings to not speak the content of text areas could be part of a solution (i.e. setting Verbosity > Speech > Text Area to “Custom” and unchecking “Content” in the VoiceOver utility.)

**Comment by slannon97** [comment]
You may want to consider adding that to the app description as a tip for VoiceOver users. I tried the setting and all it seems to do is prevent VoiceOver from automatically reading content in an edit box when you move the cursor to one.

**Comment by angstsmurf** [comment]
> I tried the setting and all it seems to do is prevent VoiceOver from automatically reading content in an edit box when you move the cursor to one.

Yes, you will want to switch the setting back to speaking Content again once you have finished using Spatterlight. Which means that it might be more trouble than it is worth. Also, it will only affect what happens when you start a game or navigate back to a game from another window, so that the method `windowDidBecomeKey` is called.

Now that I think about it, it is probably only really worth it when playing *Journey* using VoiceOver, as that is done using system menus and triggers `windowDidBecomeKey` on every turn.

**Comment by slannon97** [comment]
You can create a VoiceOver activity that changes this setting when you're in the Spatterlight window. If you close the app or move away, VoiceOver returns to its default settings and/or any activities you may have configured in other places.

**Comment by angstsmurf** [comment]
Thanks, I didn't know that. I will add that to the "VoiceOver for Spatterlight" documentation that I'm working on.
